### ISSUE TITLE
Occasional crashing on Arch

### ISSUE THREAD

**Issue by danlamanna** [werman/noise-suppression-for-voice#43]
After selecting an input source I'll get this output, followed by the output of journalctl:

```
alsa_input.usb-Blue_Microphones_Yeti_Stereo_Microphone_797_2018_07_17_00046-00.analog-stereo
/home/work/.cache/cadmus/librnnoise_ladspa.so
Traceback (most recent call last):
  File "main.py", line 142, in <module>
  File "main.py", line 125, in enable_noise_suppression
  File "main.py", line 37, in load_modules
  File "pulsectl/pulsectl.py", line 655, in module_load
  File "contextlib.py", line 88, in __exit__
  File "pulsectl/pulsectl.py", line 482, in _pulse_op_cb
pulsectl.pulsectl.PulseOperationFailed: 2
```

```
Jul 11 10:15:45  pulseaudio[306484]: [pulseaudio] module-ladspa-sink.c: Failed to parse, validate or set control parameters
Jul 11 10:15:45  pulseaudio[306484]: [pulseaudio] module.c: Failed to load module "module-ladspa-sink" (argument: "sink_name=mic_raw_in sink_master=mic_denoised_out label=noise_suppressor_mono plugin=/home/work/.cache/cadmus/librnnoise_ladspa.so sink_properties="device.description='Cadmus Raw Microphone Redirect'""): initialization failed.
Jul 11 10:15:45  pulseaudio[306484]: [pulseaudio] module-loopback.c: No such sink.
Jul 11 10:15:45  pulseaudio[306484]: [pulseaudio] module.c: Failed to load module "module-loopback" (argument: "latency_msec=1 source=alsa_input.usb-Blue_Microphones_Yeti_Stereo_Microphone_797_2018_07_17_00046-00.analog-stereo sink=mic_raw_in channels=1"): initialization failed.
```

When I can successfully start Cadmus and choose an audio input, the Cadmus output device registers as hearing no audio.

**Comment by danlamanna** [comment]
Whoops, wrong repo.
